text = " I lEARN python language"
text = text.upper()
print(text)
text = text.lower()
print(text)
text = text.strip()
print(text)
text = text.capitalize()
print(text)
new_text = text.replace("I", "we")
print(new_text)
text_count = text.count("e")
print(text_count)
text_find = text.find("n")
print(text_find)