text = " I lEARN python language"
text = text.upper()
print(text)
text = text.lower()
print(text)
text = text.strip()
print(text)
text = text.capitalize()
print(text)
new_text = text.replace("I", "we")
print(new_text)
text_count = text.count("e")
print(text_count)
print(text)
text_find = text.find("n")
print(text_find)
start_text = text.startswith("I")
print(start_text)
end_text = text.endswith("language")
print(end_text)
sp_text = text.split()
print(sp_text)
back_to_text = " ".join(sp_text)
print(back_to_text)